services:
  nifi:
    image: apache/nifi:1.28.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=qwertyuiopo1
      - NIFI_WEB_PROXY_HOST=localhost:8443,127.0.0.1:8443,nifi:8443,nifi
    volumes:
      - ./nifi/dati_csv:/opt/workspace/input_data
      - ./hdfs/config:/opt/hadoop/etc/hadoop:ro
    networks:
      - hdfs_network
    restart: always
    depends_on:
      - namenode
      - datanode

  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./hdfs/namenode:/opt/hadoop/data/nameNode
      - ./hdfs/config:/opt/hadoop/etc/hadoop
      - ./hdfs/start-hdfs.sh:/start-hdfs.sh
      - ./hdfs/config/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
    ports:
      - "9870:9870"
      - "9000:9000" # Porta RPC per la comunicazione dati
    command: [ "/bin/bash", "/start-hdfs.sh" ]
    restart: always
    networks:
      - hdfs_network

  datanode:
    image: apache/hadoop:3.4.1
    container_name: datanode
    hostname: datanode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./hdfs/datanode:/opt/hadoop/data/dataNode # Corretto percorso locale per coerenza
      - ./hdfs/config:/opt/hadoop/etc/hadoop      # Usiamo la stessa cartella config del namenode
      - ./hdfs/init-datanode.sh:/init-datanode.sh
      - ./hdfs/config/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
    depends_on:
      - namenode
    command: [ "/bin/bash", "/init-datanode.sh" ]
    restart: always
    networks:
      - hdfs_network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - hdfs_network

  airflow-webserver:
      build:
        context: .
        dockerfile: Dockerfile.airflow
      container_name: airflow-webserver
      depends_on:
        airflow-init:
          condition: service_completed_successfully
      user: "1000:0"
      environment:
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW_UID=1000
        - AIRFLOW_CONN_NIFI_DEFAULT=https://admin:qwertyuiopo1@nifi:8443?verify=false
        - AIRFLOW_CONN_HDFS_DEFAULT=webhdfs://namenode:9870
        - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark%3A%2F%2Fspark-master:7077
        - HADOOP_USER_NAME=root
      volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./airflow/logs:/opt/airflow/logs
        - ./spark/spark_scripts:/opt/spark/scripts
      ports:
        - "8081:8080"
      command: webserver
      networks:
        - hdfs_network

  airflow-scheduler:
      build:
        context: .
        dockerfile: Dockerfile.airflow

      container_name: airflow-scheduler
      depends_on:
        airflow-init:
          condition: service_completed_successfully
      user: "1000:0"
      environment:
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW_UID=1000
        - AIRFLOW_CONN_NIFI_DEFAULT=https://admin:qwertyuiopo1@nifi:8443?verify=false
        - AIRFLOW_CONN_HDFS_DEFAULT=webhdfs://namenode:9870
        - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark%3A%2F%2Fspark-master:7077
        - HADOOP_USER_NAME=root
      volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./airflow/logs:/opt/airflow/logs
        - ./spark/spark_scripts:/opt/spark/scripts
      command: scheduler
      networks:
        - hdfs_network


  airflow-init:
      build:
        context: .
        dockerfile: Dockerfile.airflow
      user: "1000:0"
      environment:
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - _AIRFLOW_DB_UPGRADE=true
        - _AIRFLOW_WWW_USER_CREATE=true
        - _AIRFLOW_WWW_USER_USERNAME=admin
        - _AIRFLOW_WWW_USER_PASSWORD=admin
        - AIRFLOW_UID=1000
        - AIRFLOW_CONN_NIFI_DEFAULT=https://admin:qwertyuiopo1@nifi:8443?verify=false
        - AIRFLOW_CONN_HDFS_DEFAULT=webhdfs://namenode:9870
        - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
      command: db migrate
      depends_on:
        - postgres
      networks:
        - hdfs_network


  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    user: root
    command: /opt/spark/sbin/start-master.sh
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_NO_DAEMONIZE=true
      - HADOOP_CONF_DIR=/opt/spark/conf/hadoop-conf
      - HADOOP_USER_NAME=root
      - PYSPARK_PYTHON=/usr/bin/python3.12
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
    volumes:
      - ./hdfs/config:/opt/spark/conf/hadoop-conf:ro
      - ./spark/spark_scripts:/opt/spark/scripts
    networks:
      - hdfs_network

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    user: root
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_NO_DAEMONIZE=true
      - HADOOP_CONF_DIR=/opt/spark/conf/hadoop-conf
      - HADOOP_USER_NAME=root
      - PYSPARK_PYTHON=/usr/bin/python3.12
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12
    depends_on:
      - spark-master
    volumes:
      - ./hdfs/config:/opt/spark/conf/hadoop-conf:ro
      - ./spark/spark_scripts:/opt/spark/scripts
    networks:
      - hdfs_network
    deploy:
      replicas: 2

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hdfs_network
    environment:
      - REDIS_ARGS=--requirepass qwertyuiopo1
    volumes:
      - ./redis/data:/data
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "472"
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource,grafana-image-renderer
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_RENDERING_RENDERER_TOKEN=token
    networks:
      - hdfs_network
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/datasources/redis.yaml:/etc/grafana/provisioning/datasources/redis.yaml
    depends_on:
      - redis
      - renderer
    restart: always



  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-renderer
    ports:
       - "8082:8081"
    environment:
      - AUTH_TOKEN=token
    networks:
      - hdfs_network
    restart: always

networks:
  hdfs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
