apiVersion: 1

datasources:
  - name: Redis-Source
    type: redis-datasource
    access: proxy
    url: redis:6379
    isDefault: true
    editable: false
    jsonData:
      poolSize: 5
    secureJsonData:
      password: "qwertyuiopo1"